# ==============================================================================
# file_uploader module inputs
#
# This module creates the full "file uploader" stack:
# - S3 bucket(s) for uploads (optionally with transfer acceleration)
# - DynamoDB table for file metadata
# - Lambda functions (upload URL presigner, file processing, etc.)
# - API Gateway + custom domain, optional WAF, and DNS (Route53)
# - Optional antivirus / file scanning integration (BucketAV)
# ==============================================================================

# ==============================================================================
# Global / environment context (used for naming + tagging everywhere)
# ==============================================================================

# Deployment environment name. Used as a prefix in many resource names.
# Examples: "ephemeral", "staging", "prod".
variable "environment" {
  description = "The environment for the deployment (e.g., dev, staging, prod)"
  type        = string
  default     = "staging"
}

# Application identifier used in tags and resource names.
# Keep short; it shows up in many AWS resource names.
variable "app_id" {
  description = "A short identifier for the application (used in tags)"
  type        = string
  default     = "file-uploader"
}

# Region where resources are created (also used by some resources for configuration).
variable "region" {
  description = "The AWS region to deploy resources"
  type        = string
  default     = "eu-central-1"
}

# ==============================================================================
# Domain / TLS (API Gateway custom domain + Route53 record)
# ==============================================================================

# Public Route53 zone where the API record will be created.
# Example: "example.com"
variable "route53_zone_name" {
  description = "Route 53 zone name (e.g., example.com)"
  type        = string
}

# Fully qualified domain name (FQDN) of the API custom domain.
# Example: "staging-api-file-upload.example.com"
variable "api_file_upload_domain_name" {
  description = "The domain name for the API to get pre-signed file upload URLs"
  type        = string
  default     = "api-file-upload.example.com"
}

# ACM certificate ARN for the API Gateway custom domain.
# This is typically created/validated outside this module.
variable "backend_certificate_arn" {
  description = "The ARN of the ACM certificate"
  type        = string
}

variable "cloudfront_domain_name" {
  description = "The  domain name for CloudFront distribution for CORS settings"
  type        = string
}

variable "cognito_user_pool_client_id" {
  type = string
}

variable "cognito_user_pool_id" {
  type = string
}

# ==============================================================================
# S3 uploads bucket settings
# ==============================================================================

# S3 bucket name to store uploads (and related objects like thumbnails).
variable "uploads_bucket_name" {
  description = "The name of the S3 bucket for file uploads"
  type        = string
  default     = "uploads-bucket"
}

# When true, S3 Transfer Acceleration is enabled for faster global uploads.
# Note: may have additional cost and requires the bucket name to be DNS compatible.
variable "enable_transfer_acceleration" {
  type        = bool
  description = "Enable S3 Transfer Acceleration?"
  default     = false
}

# ==============================================================================
# Lambda behavior knobs (timeouts/expirations/memory)
# ==============================================================================

# Expiration time (seconds) for the pre-signed PUT URL generated by the upload lambda.
variable "lambda_upload_presigned_url_expiration_time_s" {
  description = "Expiration time in seconds for the pre-signed URL generated by the upload Lambda function"
  type        = number
  default     = 300 # 5 min
}

# Expiration time (seconds) for the pre-signed GET URLs generated by the list/get lambda.
variable "lambda_get_files_presigned_url_expiration_time_s" {
  description = "Expiration time in seconds for the pre-signed URL generated by the upload Lambda function"
  type        = number
  default     = 300 # 5 min
}

# Memory size for the file-processing lambda. Higher memory often means faster execution.
variable "lambda_memory_size_mb" {
  description = "Memory size in MB value for Lambda processing file which allow faster execution"
  type        = number
  default     = 512
}

# ==============================================================================
# Optional antivirus scanning integration (BucketAV)
# ==============================================================================

# Enable/disable the BucketAV integration.
variable "use_bucket_av" {
  description = "Use BucketAV to prevent malware to be uploaded in S3 bucket"
  type        = bool
  default     = false
}

# SNS topic name where BucketAV publishes findings (clean/infected/etc).
# Required if `use_bucket_av = true`.
variable "bucket_av_sns_findings_topic_name" {
  description = "Name of SNS topics where BucketAV publishes findings"
  type        = string
  default     = ""
}

# ==============================================================================
# 7) Monitoring / notifications
# ==============================================================================

# Email address used for SNS notifications/alerts.
variable "notification_email" {
  description = "Email address for notifications"
  type        = string
}